import type { Metadata } from "next";
import "./globals.css";
import Header from "./common/header";
import Footer from "./common/footer";



export const metadata: Metadata = {
  title: "First Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {

  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Header />
        <main>
          {children}
        </main>
        <Footer />

      </body>
    </html>
  );


}
